version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=tedolijst
      - DB_USERNAME=laravel
      - DB_PASSWORD=root
