name: Laravel Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start containers
      run: docker compose -f docker-compose.yml up -d --build

    - name: Wait for MySQL to be ready
      run: |
        echo "⏳ Wachten op MySQL..."
        sleep 20

    - name: Install Composer dependencies
      run: docker exec laravel_app composer install

    - name: Copy .env file
      run: docker exec laravel_app cp .env.example .env

    - name: Generate app key
      run: docker exec laravel_app php artisan key:generate

    - name: Run migrations
      run: docker exec laravel_app php artisan migrate --force


